version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moviz_frontend
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
volumes:
  mongo_db: {}
